image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "gitlab.lilabrandon.fr:5005/mimifan/portfolio:main"

before_script:
  # Installation de Node.js
  - apk add --no-cache nodejs npm
  - npm install
  - echo "$CI_ACCESS_TOKEN" | docker login $CI_REGISTRY_HOST -u "$CI_REGISTRY_USER" --password-stdin 

build:
  stage: build
  script:
    - npm run build
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

deploy:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan lilabrandon.fr >> ~/.ssh/known_hosts
  script:
    - echo "$CI_ACCESS_TOKEN" | docker login $CI_REGISTRY_HOST -u "$CI_REGISTRY_USER" --password-stdin 
    - ssh -i ~/.ssh/id_rsa root@lilabrandon.fr "
        echo \"$CI_ACCESS_TOKEN\" | docker login $CI_REGISTRY_HOST -u \"$CI_REGISTRY_USER\" --password-stdin &&
        docker ps -q --filter 'ancestor=$DOCKER_IMAGE' | xargs -r docker stop | xargs -r docker rm &&
        docker pull $DOCKER_IMAGE &&
        docker run -d -p 3000:4174 $DOCKER_IMAGE
      "
  only:
    - main
